### ISSUE TITLE
Combine/group work on .selector encapsutated media queries

### ISSUE THREAD

**Issue by mistergraphx** [SE7ENSKY/group-css-media-queries#11]
Hi and thx for your work,

i just realised that media-queries are combine if they are defined in a selector, and not if they are the first level of css declaration.

example:

```scss
.test {
    @include media('>phone','<tablet'){
        color: blue;
    }
    @include media('<desktop'){
        color: green;
    }
}
```

result: 
```css
@media (min-width: 431px) and (max-width: 767px) {
  .test {
    color: blue;
  }
}

@media (max-width: 1023px) {
  .test {
    color: green;
  }
}
```

if i use it in multiples files like this:

```scss
// Layout.scss
@include media('<desktop'){
    *, *:before, *:after {
      box-sizing: border-box;
    }

    body,
    body.large,
    body.etroit{
        min-width: 100%; // Surcharge des spip.css 
    }
   ...
// Navigation.scss
@include media('<desktop'){
    #bando_navigation {
        border-right: 1px solid silver;
        width: 120px;
        min-height: 100%;
        position: fixed;
        top: 0;
        left: 0;
  ...
```

the grouping is ignore and there is one media-querie by imported files .

does i'm right ?
