### ISSUE TITLE
does this tool work?

### ISSUE THREAD

**Issue by cyrfer** [SE7ENSKY/group-css-media-queries#12]
I tried this project and I saw no change in the output. A new file was created, but the new file still suffered from issues of the source file. I have a ton of media queries from Less transpiling to CSS that I want to group for proper selection and optimization.

Does this project actually work?

Here were my steps to test it:
- I installed via: `npm i --save-dev group-css-media-queries`
- I made a npm script to run it, `"groupcss" : "group-css-media-queries myinput.css myoutput.css"`
- I ran my npm script, `npm run groupcss`
- I opened the new file and compared with the source, and I saw no differences.

**Comment by ivankravchenko** [comment]
Should work :)
Could you provide sample of your input file?

**Comment by cyrfer** [comment]
Thank you for looking at the problem. I am attaching my input.

[input.zip](https://github.com/SE7ENSKY/group-css-media-queries/files/392896/input.zip)

**Comment by ivankravchenko** [comment]
I've run it locally with provided input, it turns this:
```css
@media (orientation: landscape) and (min-width: 415px) {
  .col-0-landscape {
    width: 0%
  }
}

@media (orientation: landscape) and (min-width: 415px) {
  .col-offset-0-landscape {
    margin-left: 0%
  }
}

@media (orientation: landscape) and (min-width: 415px) {
  .flex-item-h-0-landscape {
    width: 0%;
    flex-basis: 0%
  }
}
```
into
```css
@media (orientation: landscape) and (min-width: 415px) {
  .col-0-landscape {
    width: 0%;
  }

  .col-offset-0-landscape {
    margin-left: 0%;
  }

  .flex-item-h-0-landscape {
    width: 0%;
    flex-basis: 0%;
  }
  /* ... other rules with same media query... */
```

Please make sure you use latest 1.2.0 version.
